import { drawObstacle } from './obstacle-icons.js';
(()=>{'use strict';
const $=s=>document.querySelector(s), canvas=$('#courseCanvas'),ctx=canvas.getContext('2d'),frame=$('#frame');
const names={jump:'Skok pojedynczy',spread:'Skok podwójny',triple:'Skok potrójny',wall:'Ściana / panel',longJump:'Skok w dal',tire:'Koło',aFrame:'Palizada A',dogWalk:'Kładka',seesaw:'Huśtawka',tunnel:'Tunel otwarty',chute:'Tunel miękki',weave:'Slalom'};
let state={title:'Mój pierwszy tor',length:40,width:24,gridSize:2,unit:'m',bg:'#f0ede1',ob:'#2b4d3e',path:'#f07851',grid:true,showRoute:true,showNumbers:true,obstacles:[],route:[],routeBends:{},selected:null,tool:'select',zoom:100,view:'2d'};
let hist=[],future=[],drag=null,dragCurve=null,changedTimer,toastTimer;
function seed(){state.obstacles=[{id:id(),type:'jump',x:.2,y:.3,n:1,label:'',rotation:0},{id:id(),type:'tunnel',x:.43,y:.28,n:2,label:'',rotation:0,length:4.5},{id:id(),type:'weave',x:.68,y:.24,n:3,label:'',rotation:0},{id:id(),type:'aFrame',x:.78,y:.54,n:4,label:'',rotation:0},{id:id(),type:'dogWalk',x:.5,y:.72,n:5,label:'',rotation:0},{id:id(),type:'tire',x:.23,y:.7,n:6,label:'',rotation:0}];state.route=[];state.routeBends={}}
function id(){return Math.random().toString(36).slice(2,10)}
function snapshot(){return JSON.stringify({...state,selected:null,tool:'select'})}function saveHistory(){hist.push(snapshot());if(hist.length>80)hist.shift();future=[]}
function restore(s){const q=JSON.parse(s);Object.assign(state,q);state.routeBends||={};state.obstacles=state.obstacles.filter(o=>!['table','marker'].includes(o.type));state.selected=null;sync();draw()}
function undo(){if(!hist.length)return;future.push(snapshot());restore(hist.pop());toast('Cofnięto zmianę')}
function redo(){if(!future.length)return;hist.push(snapshot());restore(future.pop());toast('Przywrócono zmianę')}
function sync(){ $('#title').value=state.title;$('#settingsTitle').value=state.title;$('#length').value=state.length;$('#width').value=state.width;$('#gridSize').value=state.gridSize;$('#unit').value=state.unit;$('#bgColor').value=state.bg;$('#obColor').value=state.ob;$('#pathColor').value=state.path;setSwitch('gridSwitch',state.grid);setSwitch('routeSwitch',state.showRoute);setSwitch('routeSwitch2',state.showRoute);setSwitch('numberSwitch',state.showNumbers);$('#zoomLabel').textContent=state.zoom+'%';document.querySelectorAll('[data-view]').forEach(b=>{const active=b.dataset.view===state.view;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});selectToolUI();updateStats();updateRouteList();updateSelection() }
function setSwitch(id,on){const b=document.getElementById(id);if(b)b.classList.toggle('on',!!on)}
function setTool(t){state.tool=t;document.querySelectorAll('.tool[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));$('#toolNotice').textContent=t==='route'?'Narzędzie: przeciągaj uchwyty, aby zmieniać łuki':t==='measure'?'Narzędzie: kliknij dwa punkty, aby zmierzyć':'Narzędzie: wybierz i przeciągnij';$('#hint').innerHTML=t==='route'?'<b>Trasa automatyczna</b> · Przeciągnij uchwyt na linii, aby zmienić łuk':'<b>Wskazówka</b> · Kliknij przeszkodę, aby ją zaznaczyć'}
function selectToolUI(){document.querySelectorAll('.tool[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===state.tool))}
function dim(){return {w:canvas.width,h:canvas.height}}
function routeNodes(){return [...state.obstacles].sort((a,b)=>a.n-b.n)}
function curveFor(nodes,index){const {w,h}=dim(),a=nodes[index],b=nodes[index+1];if(!a||!b)return null;const prev=nodes[index-1]||a,next=nodes[index+2]||b;
 const p0={x:a.x*w,y:a.y*h},p3={x:b.x*w,y:b.y*h},pp={x:prev.x*w,y:prev.y*h},pn={x:next.x*w,y:next.y*h};
 const dx=p3.x-p0.x,dy=p3.y-p0.y,len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len,offset=(state.routeBends?.[`${a.id}:${b.id}`]||0)*Math.min(w,h),ra=(Number(a.rotation)||0)*Math.PI/180,rb=(Number(b.rotation)||0)*Math.PI/180,align=len*.12;
 return {a,b,p0,p3,c1:{x:p0.x+(p3.x-pp.x)*.18+nx*offset+Math.cos(ra)*align,y:p0.y+(p3.y-pp.y)*.18+ny*offset+Math.sin(ra)*align},c2:{x:p3.x-(pn.x-p0.x)*.18+nx*offset-Math.cos(rb)*align,y:p3.y-(pn.y-p0.y)*.18+ny*offset-Math.sin(rb)*align},nx,ny,key:`${a.id}:${b.id}`};}
function pointOnCurve(c,t){const u=1-t;return{x:u*u*u*c.p0.x+3*u*u*t*c.c1.x+3*u*t*t*c.c2.x+t*t*t*c.p3.x,y:u*u*u*c.p0.y+3*u*u*t*c.c1.y+3*u*t*t*c.c2.y+t*t*t*c.p3.y}}
function curveSamples(c,steps=24){return Array.from({length:steps+1},(_,i)=>pointOnCurve(c,i/steps))}
function routeLength(nodes=routeNodes()){const {w,h}=dim();let total=0;for(let i=0;i<nodes.length-1;i++){const pts=curveSamples(curveFor(nodes,i));for(let j=1;j<pts.length;j++)total+=Math.hypot((pts[j].x-pts[j-1].x)/w*state.length,(pts[j].y-pts[j-1].y)/h*state.width)}return total}
function projection(){const {w,h}=dim();return{a:.78,b:.12,c:-.16,d:.62,e:w*.18,f:h*.15}}
function draw(){const {w,h}=dim(),g=state.gridSize/(state.length||40)*w;ctx.clearRect(0,0,w,h);ctx.fillStyle=state.bg;ctx.fillRect(0,0,w,h);ctx.save();if(state.view==='3d'){const p=projection();ctx.transform(p.a,p.b,p.c,p.d,p.e,p.f)}ctx.fillStyle=state.view==='3d'?'#e3dfd2':state.bg;ctx.fillRect(0,0,w,h);ctx.strokeStyle='#66776c';ctx.lineWidth=2;ctx.strokeRect(1,1,w-2,h-2);if(state.grid&&g>2){ctx.save();ctx.strokeStyle='#87948935';ctx.lineWidth=1;for(let x=0;x<=w;x+=g){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<=h;y+=g){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.restore()}
 const nodes=routeNodes();if(state.showRoute&&nodes.length>1){ctx.save();ctx.strokeStyle=state.path;ctx.lineWidth=5;ctx.lineCap='round';ctx.lineJoin='round';ctx.setLineDash([10,7]);for(let i=0;i<nodes.length-1;i++){const c=curveFor(nodes,i),pts=curveSamples(c);ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);pts.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.stroke();const p=pointOnCurve(c,.56),q=pointOnCurve(c,.58),angle=Math.atan2(q.y-p.y,q.x-p.x);ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(p.x+8*Math.cos(angle),p.y+8*Math.sin(angle));ctx.lineTo(p.x-6*Math.cos(angle-.55),p.y-6*Math.sin(angle-.55));ctx.lineTo(p.x-6*Math.cos(angle+.55),p.y-6*Math.sin(angle+.55));ctx.closePath();ctx.fillStyle=state.path;ctx.fill();ctx.setLineDash([10,7]);if(state.tool==='route'){const handle=pointOnCurve(c,.5);ctx.beginPath();ctx.arc(handle.x,handle.y,8,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle=state.path;ctx.lineWidth=3;ctx.stroke();ctx.lineWidth=5}}
 ctx.restore()}
state.obstacles.forEach(o=>drawObstacle(ctx,canvas,o,o.id===state.selected,state));ctx.restore();updateStats()}
function updateStats(){const nodes=routeNodes();$('#courseStats').textContent=`${state.obstacles.length} przeszkód · ${routeLength(nodes).toFixed(1)} ${state.unit} trasy`;$('#routeCount').textContent=`${nodes.length} przeszkód`}
function updateRouteList(){const box=$('#routeList'),nodes=routeNodes();if(!nodes.length){box.innerHTML='<div class="property-empty">Dodaj przeszkody — trasa i jej kolejność zostaną utworzone automatycznie.</div>';return}box.innerHTML=nodes.map((o,i)=>`<div class="route-item"><span class="route-num">${i+1}</span><span>${o.label||names[o.type]}</span><small>${(o.x*state.length).toFixed(1)}, ${(o.y*state.width).toFixed(1)} ${state.unit}</small></div>`).join('')}
function updateSelection(){const o=state.obstacles.find(o=>o.id===state.selected);$('#obstacleProp').classList.toggle('show',!!o);$('#emptySelection').style.display=o?'none':'block';$('#selectedType').textContent=o?names[o.type]:'—';if(o){o.rotation=Number(o.rotation)||0;$('#obstacleNum').value=o.n;$('#obstacleRotation').value=o.rotation;$('#obstacleLabel').value=o.label||'';const isTunnel=o.type==='tunnel';$('#tunnelLengthField').hidden=!isTunnel;if(isTunnel){o.length=Number(o.length)||4.5;$('#tunnelLength').value=o.length;$('#tunnelLengthValue').textContent=`${o.length.toFixed(1).replace('.',',')} m`}}}
function coords(e){const r=canvas.getBoundingClientRect();let x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;if(state.view==='3d'){const p=projection(),det=p.a*p.d-p.b*p.c,px=x*canvas.width-p.e,py=y*canvas.height-p.f;x=(p.d*px-p.c*py)/det/canvas.width;y=(-p.b*px+p.a*py)/det/canvas.height}return{x,y}}
function hit(p){for(let i=state.obstacles.length-1;i>=0;i--){const o=state.obstacles[i],dx=(p.x-o.x)*canvas.width,dy=(p.y-o.y)*canvas.height;if(Math.abs(dx)<47&&Math.abs(dy)<47)return o}return null}
function nearestCurve(p){const nodes=routeNodes(),{w,h}=dim();let best=null;for(let i=0;i<nodes.length-1;i++){const c=curveFor(nodes,i),pts=curveSamples(c,32);for(let j=0;j<pts.length;j++){const d=Math.hypot(pts[j].x-p.x*w,pts[j].y-p.y*h);if(!best||d<best.distance)best={curve:c,distance:d}}}return best}
function pointerDown(e){const p=coords(e);if(state.tool==='route'){const match=nearestCurve(p);if(!match||match.distance>26){toast('Złap uchwyt na linii trasy i przeciągnij go, aby utworzyć łuk');return}saveHistory();const c=match.curve;dragCurve={key:c.key,nx:c.nx,ny:c.ny,start:p,bend:state.routeBends[c.key]||0,moved:false};canvas.setPointerCapture(e.pointerId);return}if(state.tool==='measure'){if(!window.measureStart){window.measureStart=p;toast('Wybierz punkt końcowy')}else{const a=window.measureStart,dist=Math.hypot((p.x-a.x)*state.length,(p.y-a.y)*state.width);window.measureStart=null;toast(`Dystans: ${dist.toFixed(2)} ${state.unit}`)}return}const o=hit(p);if(o){state.selected=o.id;drag={id:o.id,dx:p.x-o.x,dy:p.y-o.y,moved:false};canvas.setPointerCapture(e.pointerId)}else{state.selected=null;drag=null}updateSelection();draw()}
function pointerMove(e){const p=coords(e);$('#coord').textContent=`${(p.x*state.length).toFixed(1)} × ${(p.y*state.width).toFixed(1)} ${state.unit}`;if(dragCurve){const {w,h}=dim(),scale=Math.min(w,h),dx=(p.x-dragCurve.start.x)*w,dy=(p.y-dragCurve.start.y)*h;state.routeBends[dragCurve.key]=Math.max(-.28,Math.min(.28,dragCurve.bend+(dx*dragCurve.nx+dy*dragCurve.ny)/scale));dragCurve.moved=true;draw();return}if(!drag)return;const o=state.obstacles.find(o=>o.id===drag.id);if(!o)return;if(!drag.moved){saveHistory();drag.moved=true}o.x=Math.max(.06,Math.min(.94,p.x-drag.dx));o.y=Math.max(.08,Math.min(.92,p.y-drag.dy));draw();updateRouteList()}
function pointerUp(){if(drag?.moved||dragCurve?.moved)markDirty();drag=null;dragCurve=null}
function addObstacle(type){saveHistory();let n=state.obstacles.reduce((a,o)=>Math.max(a,o.n),0)+1;const o={id:id(),type,x:.5,y:.5,n,label:'',rotation:0};if(type==='tunnel')o.length=4.5;state.obstacles.push(o);state.selected=o.id;state.tool='select';sync();draw();toast(`${names[type]} dodana do planszy`)}
function deleteSelected(){if(!state.selected)return;saveHistory();state.obstacles=state.obstacles.filter(o=>o.id!==state.selected);state.selected=null;updateSelection();updateRouteList();draw();toast('Usunięto przeszkodę')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1900)}
function autosave(){localStorage.setItem('agility-map-project',JSON.stringify({...state,selected:null,tool:'select'}));$('#saveState').textContent='Zapisano lokalnie';$('#saveState').parentElement.querySelector('i').style.background='var(--lime)'}
function markDirty(){ $('#saveState').textContent='Zapisywanie…';$('#saveState').parentElement.querySelector('i').style.background='var(--orange)';clearTimeout(changedTimer);changedTimer=setTimeout(autosave,450)}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportJSON(){download(new Blob([JSON.stringify({...state,selected:null,tool:'select'},null,2)],{type:'application/json'}),`${slug(state.title)}.json`);toast('Projekt zapisany do pliku')}
function slug(s){return (s||'tor-agility').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'tor-agility'}
function exportPNG(){const copy=document.createElement('canvas');copy.width=canvas.width;copy.height=canvas.height;const c=copy.getContext('2d');c.drawImage(canvas,0,0);copy.toBlob(b=>{if(b)download(b,`${slug(state.title)}.png`)},'image/png');toast('Eksport PNG gotowy')}
function toggle(id,key){state[key]=!state[key];setSwitch(id,state[key]);if(key==='showRoute')setSwitch(id==='routeSwitch'?'routeSwitch2':'routeSwitch',state[key]);draw();markDirty()}
$('#tools').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tool)setTool(b.dataset.tool);if(b.dataset.add)addObstacle(b.dataset.add)});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;sync();draw();markDirty()}));
canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',pointerUp);canvas.addEventListener('dblclick',()=>{if(state.tool==='route')setTool('select')});
$('#undo').onclick=undo;$('#redo').onclick=redo;$('#exportPng').onclick=exportPNG;$('#saveJson').onclick=exportJSON;$('#importJson').onclick=()=>$('#filePicker').click();$('#filePicker').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const q=JSON.parse(rd.result);if(!Array.isArray(q.obstacles)||!Array.isArray(q.route))throw Error();saveHistory();Object.assign(state,q);state.routeBends||={};state.obstacles=state.obstacles.filter(o=>!['table','marker'].includes(o.type));state.selected=null;sync();draw();autosave();toast('Projekt wczytany')}catch{toast('Nieprawidłowy plik projektu')}};rd.readAsText(f);e.target.value=''};
$('#gridSwitch').onclick=()=>toggle('gridSwitch','grid');$('#routeSwitch').onclick=()=>toggle('routeSwitch','showRoute');$('#routeSwitch2').onclick=()=>toggle('routeSwitch2','showRoute');$('#numberSwitch').onclick=()=>toggle('numberSwitch','showNumbers');$('#clearRoute').onclick=()=>{if(!Object.keys(state.routeBends||{}).length)return;saveHistory();state.routeBends={};draw();updateRouteList();markDirty();toast('Przywrócono automatyczne łuki')};$('#clearCourse').onclick=()=>{saveHistory();state.obstacles=[];state.route=[];state.routeBends={};state.selected=null;sync();draw();markDirty();toast('Plansza wyczyszczona')};$('#deleteObstacle').onclick=deleteSelected;
$('#obstacleNum').onchange=e=>{const o=state.obstacles.find(o=>o.id===state.selected);if(o){saveHistory();o.n=Math.max(1,Math.min(99,+e.target.value||1));draw();updateRouteList();markDirty()}};$('#obstacleRotation').onfocus=()=>saveHistory();$('#obstacleRotation').oninput=e=>{const o=state.obstacles.find(o=>o.id===state.selected);if(o){o.rotation=Math.max(-180,Math.min(180,+e.target.value||0));draw();markDirty()}};$('#tunnelLength').onpointerdown=()=>saveHistory();$('#tunnelLength').oninput=e=>{const o=state.obstacles.find(o=>o.id===state.selected);if(o?.type==='tunnel'){o.length=+e.target.value;$('#tunnelLengthValue').textContent=`${o.length.toFixed(1).replace('.',',')} m`;draw();markDirty()}};$('#obstacleLabel').oninput=e=>{const o=state.obstacles.find(o=>o.id===state.selected);if(o){o.label=e.target.value;draw();updateRouteList();markDirty()}};
const fields={title:'title',settingsTitle:'title',length:'length',width:'width',gridSize:'gridSize',unit:'unit',bgColor:'bg',obColor:'ob',pathColor:'path'};Object.keys(fields).forEach(id=>{$('#'+id).addEventListener('input',e=>{const k=fields[id];state[k]=['length','width','gridSize'].includes(k)?Math.max(.5,+e.target.value||1):e.target.value;if(k==='title'){ $('#title').value=state.title;$('#settingsTitle').value=state.title}draw();updateRouteList();markDirty()})});
$('#zoomIn').onclick=()=>{state.zoom=Math.min(150,state.zoom+10);$('#zoomLabel').textContent=state.zoom+'%';frame.style.width=`${Math.min(state.zoom,100)}%`;frame.style.transform=`scale(${state.zoom>100?state.zoom/100:1})`;};$('#zoomOut').onclick=()=>{state.zoom=Math.max(60,state.zoom-10);$('#zoomLabel').textContent=state.zoom+'%';frame.style.width=`${Math.min(state.zoom,100)}%`;frame.style.transform=`scale(${state.zoom>100?state.zoom/100:1})`};$('#fit').onclick=()=>{state.zoom=100;frame.style.width='min(100%,900px)';frame.style.transform='';$('#zoomLabel').textContent='100%'};
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if(e.key==='Delete'||e.key==='Backspace')deleteSelected();else if(e.key==='Escape')setTool('select')});
$('#showTools').onclick=()=>{$('#leftPanel').classList.toggle('mobile-open');$('#rightPanel').classList.remove('mobile-open')};$('#showSettings').onclick=()=>{$('#rightPanel').classList.toggle('mobile-open');$('#leftPanel').classList.remove('mobile-open')};
window.addEventListener('agility-icons-ready',()=>draw());
const current=localStorage.getItem('agility-map-project'),legacy=localStorage.getItem('torownik-project'),old=current||legacy;if(old){try{Object.assign(state,JSON.parse(old));state.routeBends||={};state.obstacles=state.obstacles.filter(o=>!['table','marker'].includes(o.type));state.selected=null;if(!current&&legacy)localStorage.setItem('agility-map-project',JSON.stringify(state))}catch{seed()}}else seed();sync();draw();
})()

