import { drawObstacle } from './obstacle-icons.js';
(()=>{'use strict';
const $=s=>document.querySelector(s), canvas=$('#courseCanvas'),ctx=canvas.getContext('2d'),frame=$('#frame');
const names={jump:'Stacjonata',tunnel:'Tunel',weave:'Slalom',tire:'Koło',table:'Stół',marker:'Znacznik'};
let state={title:'Mój pierwszy tor',length:40,width:24,gridSize:2,unit:'m',bg:'#f0ede1',ob:'#2b4d3e',path:'#f07851',grid:true,showRoute:true,showNumbers:true,obstacles:[],route:[],selected:null,tool:'select',zoom:100};
let hist=[],future=[],drag=null,changedTimer,toastTimer;
function seed(){state.obstacles=[{id:id(),type:'jump',x:.23,y:.27,n:1,label:''},{id:id(),type:'tunnel',x:.45,y:.28,n:2,label:''},{id:id(),type:'weave',x:.72,y:.25,n:3,label:''},{id:id(),type:'jump',x:.76,y:.55,n:4,label:''},{id:id(),type:'tire',x:.5,y:.65,n:5,label:''},{id:id(),type:'table',x:.24,y:.68,n:6,label:''}];state.route=[{x:.23,y:.27},{x:.45,y:.28},{x:.72,y:.25},{x:.76,y:.55},{x:.5,y:.65},{x:.24,y:.68}]}
function id(){return Math.random().toString(36).slice(2,10)}
function snapshot(){return JSON.stringify({...state,selected:null,tool:'select'})}function saveHistory(){hist.push(snapshot());if(hist.length>80)hist.shift();future=[]}
function restore(s){const q=JSON.parse(s);Object.assign(state,q);state.selected=null;sync();draw()}
function undo(){if(!hist.length)return;future.push(snapshot());restore(hist.pop());toast('Cofnięto zmianę')}
function redo(){if(!future.length)return;hist.push(snapshot());restore(future.pop());toast('Przywrócono zmianę')}
function sync(){ $('#title').value=state.title;$('#settingsTitle').value=state.title;$('#length').value=state.length;$('#width').value=state.width;$('#gridSize').value=state.gridSize;$('#unit').value=state.unit;$('#bgColor').value=state.bg;$('#obColor').value=state.ob;$('#pathColor').value=state.path;setSwitch('gridSwitch',state.grid);setSwitch('routeSwitch',state.showRoute);setSwitch('routeSwitch2',state.showRoute);setSwitch('numberSwitch',state.showNumbers);$('#zoomLabel').textContent=state.zoom+'%';selectToolUI();updateStats();updateRouteList();updateSelection() }
function setSwitch(id,on){const b=document.getElementById(id);if(b)b.classList.toggle('on',!!on)}
function setTool(t){state.tool=t;document.querySelectorAll('.tool[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));$('#toolNotice').textContent=t==='route'?'Narzędzie: klikaj, aby rysować trasę':t==='measure'?'Narzędzie: kliknij dwa punkty, aby zmierzyć':'Narzędzie: wybierz i przeciągnij';$('#hint').innerHTML=t==='route'?'<b>Trasa</b> · Klikaj, aby dodawać punkty · Esc, aby zakończyć':t==='measure'?'<b>Pomiar</b> · Kliknij początek i koniec odcinka':'<b>Wskazówka</b> · Kliknij przeszkodę, aby ją zaznaczyć'}
function selectToolUI(){document.querySelectorAll('.tool[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===state.tool))}
function dim(){return {w:canvas.width,h:canvas.height}}
function draw(){const {w,h}=dim(),g=state.gridSize/(state.length||40)*w;ctx.clearRect(0,0,w,h);ctx.fillStyle=state.bg;ctx.fillRect(0,0,w,h);ctx.save();ctx.strokeStyle='#66776c';ctx.lineWidth=2;ctx.strokeRect(1,1,w-2,h-2);ctx.restore();if(state.grid&&g>2){ctx.save();ctx.strokeStyle='#87948935';ctx.lineWidth=1;for(let x=0;x<=w;x+=g){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<=h;y+=g){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.restore()}
if(state.showRoute&&state.route.length){ctx.save();ctx.beginPath();state.route.forEach((p,i)=>{const x=p.x*w,y=p.y*h;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=state.path;ctx.lineWidth=5;ctx.lineCap='round';ctx.lineJoin='round';ctx.setLineDash([10,7]);ctx.stroke();ctx.setLineDash([]);state.route.forEach((p,i)=>{const x=p.x*w,y=p.y*h;ctx.beginPath();ctx.arc(x,y,14,0,Math.PI*2);ctx.fillStyle=state.path;ctx.fill();ctx.fillStyle='#fff';ctx.font='bold 13px DM Sans';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(i+1,x,y)});ctx.restore()}
state.obstacles.forEach(o=>drawObstacle(ctx,canvas,o,o.id===state.selected,state));updateStats()}
function updateStats(){let meters=0;for(let i=1;i<state.route.length;i++){const a=state.route[i-1],b=state.route[i],dx=(b.x-a.x)*state.length,dy=(b.y-a.y)*state.width;meters+=Math.hypot(dx,dy)}$('#courseStats').textContent=`${state.obstacles.length} przeszkód · ${meters.toFixed(1)} ${state.unit} trasy`;$('#routeCount').textContent=`${state.route.length} punktów`}
function updateRouteList(){let box=$('#routeList');if(!state.route.length){box.innerHTML='<div class="property-empty">Wybierz narzędzie <b>Trasa</b>, a następnie klikaj na planszy, aby wyznaczyć przebieg.</div>';return}box.innerHTML=state.route.map((p,i)=>`<div class="route-item"><span class="route-num">${i+1}</span><span>Punkt ${i+1}</span><small>${(p.x*state.length).toFixed(1)}, ${(p.y*state.width).toFixed(1)} ${state.unit}</small></div>`).join('')}
function updateSelection(){const o=state.obstacles.find(o=>o.id===state.selected);$('#obstacleProp').classList.toggle('show',!!o);$('#emptySelection').style.display=o?'none':'block';$('#selectedType').textContent=o?names[o.type]:'—';if(o){$('#obstacleNum').value=o.n;$('#obstacleLabel').value=o.label||''}}
function coords(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}}
function hit(p){for(let i=state.obstacles.length-1;i>=0;i--){const o=state.obstacles[i],dx=(p.x-o.x)*canvas.width,dy=(p.y-o.y)*canvas.height;if(Math.abs(dx)<47&&Math.abs(dy)<47)return o}return null}
function pointerDown(e){const p=coords(e);if(state.tool==='route'){saveHistory();state.route.push(p);draw();updateRouteList();return}if(state.tool==='measure'){if(!window.measureStart){window.measureStart=p;toast('Wybierz punkt końcowy')}else{const a=window.measureStart,dist=Math.hypot((p.x-a.x)*state.length,(p.y-a.y)*state.width);window.measureStart=null;toast(`Dystans: ${dist.toFixed(2)} ${state.unit}`)}return}const o=hit(p);if(o){state.selected=o.id;drag={id:o.id,dx:p.x-o.x,dy:p.y-o.y,moved:false};canvas.setPointerCapture(e.pointerId)}else{state.selected=null;drag=null}updateSelection();draw()}
function pointerMove(e){const p=coords(e);$('#coord').textContent=`${(p.x*state.length).toFixed(1)} × ${(p.y*state.width).toFixed(1)} ${state.unit}`;if(!drag)return;const o=state.obstacles.find(o=>o.id===drag.id);if(!o)return;if(!drag.moved){saveHistory();drag.moved=true}o.x=Math.max(.06,Math.min(.94,p.x-drag.dx));o.y=Math.max(.08,Math.min(.92,p.y-drag.dy));const r=state.route.find((_,i)=>state.obstacles[i]?.id===o.id);draw()}
function pointerUp(){if(drag?.moved)markDirty();drag=null}
function addObstacle(type){saveHistory();let n=state.obstacles.reduce((a,o)=>Math.max(a,o.n),0)+1;const o={id:id(),type,x:.5,y:.5,n,label:''};state.obstacles.push(o);state.selected=o.id;state.tool='select';sync();draw();toast(`${names[type]} dodana do planszy`)}
function deleteSelected(){if(!state.selected)return;saveHistory();state.obstacles=state.obstacles.filter(o=>o.id!==state.selected);state.selected=null;updateSelection();draw();toast('Usunięto przeszkodę')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1900)}
function autosave(){localStorage.setItem('torownik-project',JSON.stringify({...state,selected:null,tool:'select'}));$('#saveState').textContent='Zapisano lokalnie';$('#saveState').parentElement.querySelector('i').style.background='var(--lime)'}
function markDirty(){ $('#saveState').textContent='Zapisywanie…';$('#saveState').parentElement.querySelector('i').style.background='var(--orange)';clearTimeout(changedTimer);changedTimer=setTimeout(autosave,450)}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportJSON(){download(new Blob([JSON.stringify({...state,selected:null,tool:'select'},null,2)],{type:'application/json'}),`${slug(state.title)}.json`);toast('Projekt zapisany do pliku')}
function slug(s){return (s||'tor-agility').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'tor-agility'}
function exportPNG(){const copy=document.createElement('canvas');copy.width=canvas.width;copy.height=canvas.height;const c=copy.getContext('2d');c.drawImage(canvas,0,0);copy.toBlob(b=>{if(b)download(b,`${slug(state.title)}.png`)},'image/png');toast('Eksport PNG gotowy')}
function toggle(id,key){state[key]=!state[key];setSwitch(id,state[key]);if(key==='showRoute')setSwitch(id==='routeSwitch'?'routeSwitch2':'routeSwitch',state[key]);draw();markDirty()}
$('#tools').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tool)setTool(b.dataset.tool);if(b.dataset.add)addObstacle(b.dataset.add)});
canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',pointerUp);canvas.addEventListener('dblclick',()=>{if(state.tool==='route')setTool('select')});
$('#undo').onclick=undo;$('#redo').onclick=redo;$('#exportPng').onclick=exportPNG;$('#saveJson').onclick=exportJSON;$('#importJson').onclick=()=>$('#filePicker').click();$('#filePicker').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const q=JSON.parse(rd.result);if(!Array.isArray(q.obstacles)||!Array.isArray(q.route))throw Error();saveHistory();Object.assign(state,q);state.selected=null;sync();draw();autosave();toast('Projekt wczytany')}catch{toast('Nieprawidłowy plik projektu')}};rd.readAsText(f);e.target.value=''};
$('#gridSwitch').onclick=()=>toggle('gridSwitch','grid');$('#routeSwitch').onclick=()=>toggle('routeSwitch','showRoute');$('#routeSwitch2').onclick=()=>toggle('routeSwitch2','showRoute');$('#numberSwitch').onclick=()=>toggle('numberSwitch','showNumbers');$('#clearRoute').onclick=()=>{if(!state.route.length)return;saveHistory();state.route=[];draw();updateRouteList();markDirty()};$('#clearCourse').onclick=()=>{saveHistory();state.obstacles=[];state.route=[];state.selected=null;sync();draw();markDirty();toast('Plansza wyczyszczona')};$('#deleteObstacle').onclick=deleteSelected;
$('#obstacleNum').onchange=e=>{const o=state.obstacles.find(o=>o.id===state.selected);if(o){saveHistory();o.n=Math.max(1,Math.min(99,+e.target.value||1));draw();markDirty()}};$('#obstacleLabel').oninput=e=>{const o=state.obstacles.find(o=>o.id===state.selected);if(o){o.label=e.target.value;draw();markDirty()}};
const fields={title:'title',settingsTitle:'title',length:'length',width:'width',gridSize:'gridSize',unit:'unit',bgColor:'bg',obColor:'ob',pathColor:'path'};Object.keys(fields).forEach(id=>{$('#'+id).addEventListener('input',e=>{const k=fields[id];state[k]=['length','width','gridSize'].includes(k)?Math.max(.5,+e.target.value||1):e.target.value;if(k==='title'){ $('#title').value=state.title;$('#settingsTitle').value=state.title}draw();updateRouteList();markDirty()})});
$('#zoomIn').onclick=()=>{state.zoom=Math.min(150,state.zoom+10);$('#zoomLabel').textContent=state.zoom+'%';frame.style.width=`${Math.min(state.zoom,100)}%`;frame.style.transform=`scale(${state.zoom>100?state.zoom/100:1})`;};$('#zoomOut').onclick=()=>{state.zoom=Math.max(60,state.zoom-10);$('#zoomLabel').textContent=state.zoom+'%';frame.style.width=`${Math.min(state.zoom,100)}%`;frame.style.transform=`scale(${state.zoom>100?state.zoom/100:1})`};$('#fit').onclick=()=>{state.zoom=100;frame.style.width='min(100%,900px)';frame.style.transform='';$('#zoomLabel').textContent='100%'};
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if(e.key==='Delete'||e.key==='Backspace')deleteSelected();else if(e.key==='Escape')setTool('select')});
$('#showTools').onclick=()=>{$('#leftPanel').classList.toggle('mobile-open');$('#rightPanel').classList.remove('mobile-open')};$('#showSettings').onclick=()=>{$('#rightPanel').classList.toggle('mobile-open');$('#leftPanel').classList.remove('mobile-open')};
const old=localStorage.getItem('torownik-project');if(old){try{Object.assign(state,JSON.parse(old));state.selected=null}catch{seed()}}else seed();sync();draw();
})()

