import { drawObstacle, obstacleFootprint, obstacleEntrySide, tunnelPath } from './obstacle-icons.js?v=agility-alternate-track-color-20261003';
(()=>{'use strict';
const $=s=>document.querySelector(s), canvas=$('#courseCanvas'),ctx=canvas.getContext('2d'),frame=$('#frame'),canvasWrap=$('#canvasWrap');
const names={jump:'Skok pojedynczy',spread:'Skok podwójny',wall:'Ściana / panel',longJump:'Skok w dal',tire:'Koło',aFrame:'Palizada A',dogWalk:'Kładka',seesaw:'Huśtawka',tunnel:'Tunel otwarty',weave:'Slalom'};
let state={title:'Mój pierwszy tor',length:40,width:24,gridSize:2,unit:'m',bg:'#f0ede1',ob:'#2b4d3e',path:'#f07851',grid:true,showRoute:true,showNumbers:true,showDistances:false,obstacles:[],route:[],routeBends:{},selected:null,tool:'select',zoom:100,view:'2d'};
let hist=[],future=[],drag=null,dragCurve=null,dragRotation=null,changedTimer,toastTimer,scene3d=null,scene3dLoading=null;
let gridCacheCanvas=null,gridCacheKey='',editingVisitIndex=null;
function seed(){state.obstacles=[{id:id(),type:'jump',x:.2,y:.3,n:1,label:'',rotation:0},{id:id(),type:'tunnel',x:.43,y:.28,n:2,label:'',rotation:0,length:4.5,bend:0},{id:id(),type:'weave',x:.68,y:.24,n:3,label:'',rotation:0},{id:id(),type:'aFrame',x:.78,y:.54,n:4,label:'',rotation:0},{id:id(),type:'dogWalk',x:.5,y:.72,n:5,label:'',rotation:0},{id:id(),type:'tire',x:.23,y:.7,n:6,label:'',rotation:0}];state.route=[];state.routeBends={}}
function id(){return Math.random().toString(36).slice(2,10)}
function snapshot(){return JSON.stringify({...state,selected:null,tool:'select'})}function saveHistory(){hist.push(snapshot());if(hist.length>80)hist.shift();future=[]}
function restore(s){const q=JSON.parse(s);Object.assign(state,q);state.routeBends||={};state.showDistances=!!state.showDistances;state.obstacles=state.obstacles.filter(o=>!['table','marker','chute','triple'].includes(o.type));normalizeOrderNumbers();state.selected=null;sync();draw()}
function undo(){if(!hist.length)return;future.push(snapshot());restore(hist.pop());toast('Cofnięto zmianę')}
function redo(){if(!future.length)return;hist.push(snapshot());restore(future.pop());toast('Przywrócono zmianę')}
function updateScaleIndicator(){const indicator=$('#scaleIndicator');if(!indicator)return;if(state.view==='3d'){indicator.textContent=state.grid?`Siatka co ${(state.gridSize*(state.unit==='ft'?.3048:1)).toFixed(1)} m`:'Widok 3D · wymiary w metrach';return}const boardMeters=state.length*(state.unit==='ft'?.3048:1),pxPerMeter=canvas.getBoundingClientRect().width/Math.max(.01,boardMeters);indicator.textContent=`Skala: 1 m ≈ ${pxPerMeter.toFixed(1)} px`}
function applyZoom(){const zoom=Math.max(60,Math.min(150,Number(state.zoom)||100));state.zoom=zoom;$('#zoomLabel').textContent=zoom+'%';const css=getComputedStyle(canvasWrap),horizontal=parseFloat(css.paddingLeft)+parseFloat(css.paddingRight),vertical=parseFloat(css.paddingTop)+parseFloat(css.paddingBottom),availableWidth=Math.max(1,canvasWrap.clientWidth-horizontal),availableHeight=Math.max(1,canvasWrap.clientHeight-vertical),fitWidth=Math.min(900,availableWidth,availableHeight*1.62);frame.style.width=`${fitWidth*zoom/100}px`;frame.style.transform='';updateScaleIndicator()}
function sync(){ $('#title').value=state.title;$('#settingsTitle').value=state.title;$('#length').value=state.length;$('#width').value=state.width;$('#gridSize').value=state.gridSize;$('#unit').value=state.unit;document.querySelectorAll('[data-board-unit]').forEach(el=>el.textContent=state.unit);$('#bgColor').value=state.bg;$('#obColor').value=state.ob;$('#pathColor').value=state.path;setSwitch('gridSwitch',state.grid);setSwitch('routeSwitch',state.showRoute);setSwitch('routeSwitch2',state.showRoute);setSwitch('numberSwitch',state.showNumbers);setSwitch('distanceSwitch',state.showDistances);applyZoom();frame.dataset.view=state.view;document.querySelectorAll('[data-view]').forEach(b=>{const active=b.dataset.view===state.view;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});selectToolUI();updateStats();updateRouteList();updateSelection() }
function setSwitch(id,on){const b=document.getElementById(id);if(b)b.classList.toggle('on',!!on)}
function showError(message){const t=$('#toast');t.textContent=message;t.classList.add('show','error');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show','error'),3200)}
function openNumberEditor(obstacle,visitIndex=null){state.selected=obstacle.id;editingVisitIndex=visitIndex;updateSelection();draw();const visit=visitIndex==null?null:state.route[visitIndex];$('#numberEditDialog h2').textContent=visitIndex==null?'Edytuj numer przeszkody':'Edytuj numer tego przejścia';$('#numberEditValue').value=Number.isInteger(visit?.n)?visit.n:obstacle.n;$('#numberEditDialog').showModal();requestAnimationFrame(()=>{$('#numberEditValue').focus();$('#numberEditValue').select()})}
function normalizeOrderNumbers(){let changed=false;for(const o of state.obstacles){const n=Math.max(1,Math.min(99,Math.floor(Number(o.n)||1)));if(o.n!==n)changed=true;o.n=n}return changed}
function numberInUse(number,exceptId){return state.obstacles.some(o=>o.id!==exceptId&&Number(o.n)===number)}
function setTool(t){state.tool=t;document.querySelectorAll('.tool[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));$('#toolNotice').textContent=t==='route'?'Narzędzie: przeciągaj uchwyty, aby zmieniać łuki':'Narzędzie: wybierz i przeciągnij';$('#hint').innerHTML=t==='route'?'<b>Trasa automatyczna</b> · Przeciągnij uchwyt na linii, aby zmienić łuk':'<b>Wskazówka</b> · Kliknij numer, aby go zmienić; przeciągnij uchwyt nad przeszkodą, aby obrócić'}
function selectToolUI(){document.querySelectorAll('.tool[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===state.tool))}
function dim(){return {w:canvas.width,h:canvas.height}}
function routeNodes(){const byId=new Map(state.obstacles.map(o=>[o.id,o]));const visits=Array.isArray(state.route)?state.route.map((visit,index)=>({visit,index,key:typeof visit==='string'?visit:visit?.obstacleId})).filter(item=>byId.has(item.key)):[];return visits.length?visits.map(({visit,index,key})=>{const obstacle=byId.get(key);return{...obstacle,n:Number.isInteger(visit?.n)?visit.n:obstacle.n,_visitIndex:index,_visitKey:`${key}@${index}`}}):[...state.obstacles].sort((a,b)=>a.n-b.n)}
function obstacleTraversal(nodes,index,beforeOverride,afterOverride){const o=nodes[index];if(!o)return null;const scale=state.unit==='ft'?.3048:1,angle=(Number(o.rotation)||0)*Math.PI/180,count=Number(o.poleCount)===6?6:12,shape=o.type==='tunnel'?tunnelPath(Number(o.length)||4.5,o.bend,32):o.type==='weave'?[{x:-((count-1)*.3+.3),y:0},...Array.from({length:count},(_,i)=>({x:(i-(count-1)/2)*.6,y:i%2?.27:-.27})),{x:(count-1)*.3+.3,y:0}]:[{x:0,y:-obstacleFootprint(o).depth/2},{x:0,y:obstacleFootprint(o).depth/2}],points=shape.map(p=>({x:o.x+(p.x*Math.cos(angle)-p.y*Math.sin(angle))/(state.length*scale),y:o.y+(p.x*Math.sin(angle)+p.y*Math.cos(angle))/(state.width*scale)}));const meters=(p,q)=>Math.hypot((p.x-q.x)*state.length*scale,(p.y-q.y)*state.width*scale),before=beforeOverride||nodes[index-1],after=afterOverride||nodes[index+1];let enterFromStart;if(before)enterFromStart=meters(points[0],before)<meters(points.at(-1),before);else if(after)enterFromStart=meters(points.at(-1),after)<meters(points[0],after);else enterFromStart=true;if(!enterFromStart)points.reverse();return{entry:points[0],exit:points.at(-1),points};}
function routeConnections(nodes){const groups=[];for(let i=0;i<nodes.length;i++){const o=nodes[i],last=groups.at(-1);if(last&&Number(last[0].o.n)===Number(o.n)&&last.some(item=>item.o.id!==o.id))last.push({o,index:i});else groups.push([{o,index:i}])}for(const group of groups)group.forEach((item,variantIndex)=>item.variantIndex=variantIndex);const result=[];for(let i=0;i<groups.length-1;i++)for(const aa of groups[i])for(const bb of groups[i+1])result.push({i,ai:aa.index,bi:bb.index,a:aa.o,b:bb.o,alternate:aa.variantIndex>0||bb.variantIndex>0,prev:groups[i-1]?.[0].o||aa.o,next:groups[i+2]?.[0].o||bb.o});return result}
function curveFor(nodes,index,pair){const {w,h}=dim(),a=pair?.a||nodes[index],b=pair?.b||nodes[index+1];if(!a||!b)return null;const prev=pair?.prev||nodes[index-1]||a,next=pair?.next||nodes[index+2]||b,ai=pair?.ai??index,bi=pair?.bi??index+1,ta=obstacleTraversal(nodes,ai,prev,b),tb=obstacleTraversal(nodes,bi,a,next);
 const px=p=>({x:p.x*w,y:p.y*h}),center=o=>px({x:o.x,y:o.y}),p0=ta?px(ta.exit):center(a),p3=tb?px(tb.entry):center(b),pp=center(prev),pn=center(next);
 const dx=p3.x-p0.x,dy=p3.y-p0.y,len=Math.hypot(dx,dy)||1,nx=-dy/len,ny=dx/len,offset=(state.routeBends?.[`${a.id}:${b.id}`]||0)*Math.min(w,h),ra=(Number(a.rotation)||0)*Math.PI/180,rb=(Number(b.rotation)||0)*Math.PI/180,align=len*.2;
 const startTangent=ta?{x:(ta.exit.x-ta.points.at(-2).x)*w,y:(ta.exit.y-ta.points.at(-2).y)*h}:null,endTangent=tb?{x:(tb.points[1].x-tb.entry.x)*w,y:(tb.points[1].y-tb.entry.y)*h}:null;
 const norm=v=>{const d=Math.hypot(v.x,v.y)||1;return{x:v.x/d,y:v.y/d}},st=startTangent&&norm(startTangent),et=endTangent&&norm(endTangent);
 const c1=st?{x:p0.x+st.x*align+nx*offset,y:p0.y+st.y*align+ny*offset}:{x:p0.x+(p3.x-pp.x)*.18+nx*offset+Math.cos(ra)*align,y:p0.y+(p3.y-pp.y)*.18+ny*offset+Math.sin(ra)*align};
 const c2=et?{x:p3.x-et.x*align+nx*offset,y:p3.y-et.y*align+ny*offset}:{x:p3.x-(pn.x-p0.x)*.18+nx*offset-Math.cos(rb)*align,y:p3.y-(pn.y-p0.y)*.18+ny*offset-Math.sin(rb)*align};
 return {a,b,p0,p3,c1,c2,nx,ny,key:`${a.id}:${b.id}`,obstaclePoints:tb?.points.map(px)||null};}
function pointOnCurve(c,t){const u=1-t;return{x:u*u*u*c.p0.x+3*u*u*t*c.c1.x+3*u*t*t*c.c2.x+t*t*t*c.p3.x,y:u*u*u*c.p0.y+3*u*u*t*c.c1.y+3*u*t*t*c.c2.y+t*t*t*c.p3.y}}
function curveSamples(c,steps=24){const points=Array.from({length:steps+1},(_,i)=>pointOnCurve(c,i/steps));if(c.obstaclePoints?.length)points.push(...c.obstaclePoints.slice(1));return points}
function routeLength(nodes=routeNodes()){const {w,h}=dim();let total=0;for(const pair of routeConnections(nodes)){const pts=curveSamples(curveFor(nodes,pair.i,pair));for(let j=1;j<pts.length;j++)total+=Math.hypot((pts[j].x-pts[j-1].x)/w*state.length,(pts[j].y-pts[j-1].y)/h*state.width)}return total}
function drawDistances(nodes,w,h){if(!state.showDistances||nodes.length<2)return;ctx.save();ctx.font='700 12px "DM Sans",sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';for(const pair of routeConnections(nodes)){const c=curveFor(nodes,pair.i,pair),samples=Array.from({length:41},(_,j)=>pointOnCurve(c,j/40));let meters=0;for(let j=1;j<samples.length;j++)meters+=Math.hypot((samples[j].x-samples[j-1].x)/w*state.length,(samples[j].y-samples[j-1].y)/h*state.width);const amount=meters*(state.unit==='ft'?.3048:1),m=pointOnCurve(c,.5),mx=m.x,my=m.y-15;const text=`${amount.toFixed(1)} m`,tw=ctx.measureText(text).width+12;ctx.fillStyle='#f8f7ed';ctx.fillRect(mx-tw/2,my-10,tw,20);ctx.strokeStyle='#168d88';ctx.lineWidth=1.5;ctx.strokeRect(mx-tw/2,my-10,tw,20);ctx.fillStyle='#234b45';ctx.fillText(text,mx,my)}ctx.restore()}
function drawMetricGridLabels(w,h){
 if(!state.grid)return;
 const toMeters=state.unit==='ft'?.3048:1,length=state.length*toMeters,width=state.width*toMeters,step=state.gridSize*toMeters;
 if(!length||!width||!step)return;
 const fmt=value=>Number(value.toFixed(1)).toString().replace('.',',');
 ctx.save();ctx.font='600 10px "DM Sans",sans-serif';ctx.textBaseline='middle';
 const drawAxis=(total,pixels,vertical)=>{
  const count=Math.floor(total/step+1e-6),skip=Math.max(1,Math.ceil(count/18)),indices=[];
  for(let i=0;i<=count;i+=skip)indices.push(i);
  if(count%skip!==0)indices.push(count);
  for(const i of indices){
   const value=i===count&&count%skip!==0?total:i*step,pos=value/total*pixels,text=`${fmt(value)} m`,tw=ctx.measureText(text).width+7;
   const atEnd=pos>pixels-tw-7;
   if(vertical){const x=35,y=Math.max(22,Math.min(pixels-10,pos-4));ctx.textAlign='right';ctx.fillStyle='#fffdf0dc';ctx.fillRect(Math.max(2,x-tw-3),y-8,tw,16);ctx.fillStyle='#344b40';ctx.fillText(text,x-1,y)}
   else{const x=atEnd?pixels-4:Math.max(4,pos+4),y=16;ctx.textAlign=atEnd?'right':'left';ctx.fillStyle='#fffdf0dc';ctx.fillRect(atEnd?x-tw-3:x-3,y-8,tw,16);ctx.fillStyle='#344b40';ctx.fillText(text,atEnd?x-1:x,y)}
  }
 };
 drawAxis(length,w,false);drawAxis(width,h,true);ctx.restore()
}
function drawBoardGrid(w,h){const unitScale=state.unit==='ft'?.3048:1,key=[w,h,state.length,state.width,state.gridSize,state.unit,state.grid,state.bg].join('|');if(!gridCacheCanvas)gridCacheCanvas=document.createElement('canvas');if(gridCacheKey!==key){gridCacheCanvas.width=w;gridCacheCanvas.height=h;const board=gridCacheCanvas.getContext('2d'),gx=state.gridSize/(state.length||40)*w,gy=state.gridSize/(state.width||24)*h;board.fillStyle=state.bg;board.fillRect(0,0,w,h);board.strokeStyle='#66776c';board.lineWidth=2;board.strokeRect(1,1,w-2,h-2);if(state.grid&&gx>2&&gy>2){board.beginPath();for(let x=0;x<=w;x+=gx){board.moveTo(x,0);board.lineTo(x,h)}for(let y=0;y<=h;y+=gy){board.moveTo(0,y);board.lineTo(w,y)}board.strokeStyle='#87948935';board.lineWidth=1;board.stroke()}gridCacheKey=key}ctx.clearRect(0,0,w,h);ctx.drawImage(gridCacheCanvas,0,0);drawMetricGridLabels(w,h)}
function draw(){const {w,h}=dim();drawBoardGrid(w,h)
 const nodes=routeNodes();if(state.showRoute&&nodes.length>1){ctx.save();ctx.strokeStyle=state.path;ctx.lineWidth=5;ctx.lineCap='round';ctx.lineJoin='round';ctx.setLineDash([10,7]);for(const pair of routeConnections(nodes)){ctx.strokeStyle=pair.alternate?'#397fd0':state.path;const c=curveFor(nodes,pair.i,pair),pts=curveSamples(c);ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);pts.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.stroke();const p=pointOnCurve(c,.56),q=pointOnCurve(c,.58),angle=Math.atan2(q.y-p.y,q.x-p.x);ctx.setLineDash([]);ctx.beginPath();ctx.moveTo(p.x+8*Math.cos(angle),p.y+8*Math.sin(angle));ctx.lineTo(p.x-6*Math.cos(angle-.55),p.y-6*Math.sin(angle-.55));ctx.lineTo(p.x-6*Math.cos(angle+.55),p.y-6*Math.sin(angle+.55));ctx.closePath();ctx.fillStyle=pair.alternate?'#397fd0':state.path;ctx.fill();ctx.setLineDash([10,7]);if(state.tool==='route'){const handle=pointOnCurve(c,.5);ctx.beginPath();ctx.arc(handle.x,handle.y,8,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle=state.path;ctx.lineWidth=3;ctx.stroke();ctx.lineWidth=5}}
 ctx.restore()}
 drawDistances(nodes,w,h);state.obstacles.forEach(o=>drawObstacle(ctx,canvas,o,o.id===state.selected,state));drawRotationHandle();ctx.restore();if(state.showRoute&&nodes.length){ctx.save();ctx.setLineDash([10,7]);ctx.strokeStyle=state.path;ctx.lineWidth=3;const firstGroup=nodes.filter(o=>Number(o.n)===Number(nodes[0].n));for(const obstacle of firstGroup){ctx.strokeStyle=firstGroup.indexOf(obstacle)>0?'#397fd0':state.path;const index=nodes.indexOf(obstacle),first=obstacleTraversal(nodes,index,null,routeConnections(nodes).find(pair=>pair.ai===index)?.b)?.points.map(p=>({x:p.x*w,y:p.y*h}));if(first?.length){ctx.beginPath();ctx.moveTo(first[0].x,first[0].y);first.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.stroke()}}for(const pair of routeConnections(nodes)){ctx.strokeStyle=pair.alternate?'#397fd0':state.path;const c=curveFor(nodes,pair.i,pair);if(c.obstaclePoints?.length>1){ctx.beginPath();ctx.moveTo(c.obstaclePoints[0].x,c.obstaclePoints[0].y);c.obstaclePoints.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.stroke()}}ctx.restore()}updateScaleIndicator();updateStats();if(state.view==='3d'&&scene3d){try{scene3d.update(state)}catch(error){state.view='2d';sync();showError(`Widok 3D nie mógł się odświeżyć: ${error.message}`)}}}
function updateStats(){const nodes=routeNodes();$('#courseStats').textContent=`${state.obstacles.length} przeszkód · ${routeLength(nodes).toFixed(1)} ${state.unit} trasy`;$('#routeCount').textContent=`${nodes.length} przeszkód`}
function updateRouteList(){const box=$('#routeList'),nodes=routeNodes(),seen=new Map();if(!nodes.length){box.innerHTML='<div class="property-empty">Dodaj przeszkody — trasa i jej kolejność zostaną utworzone automatycznie.</div>';return}box.innerHTML=nodes.map(o=>{const visit=(seen.get(o.id)||0)+1;seen.set(o.id,visit);return`<div class="route-item"><span class="route-num">${o.n}</span><span>${o.label||names[o.type]}${visit>1?' · powtórzenie':''}</span><small>${(o.x*state.length).toFixed(1)}, ${(o.y*state.width).toFixed(1)} ${state.unit}</small></div>`}).join('')}
function updateSelection(){const o=state.obstacles.find(o=>o.id===state.selected);$('#obstacleProp').classList.toggle('show',!!o);$('#emptySelection').style.display=o?'none':'block';$('#selectedType').textContent=o?names[o.type]:'—';$('#weavePoleCountField').hidden=o?.type!=='weave';$('#obstacleHeightField').hidden=!o||!['aFrame','dogWalk','tire'].includes(o.type);$('#tunnelLengthField').hidden=o?.type!=='tunnel';$('#tunnelBendField').hidden=o?.type!=='tunnel';if(!o)return;o.rotation=Number(o.rotation)||0;$('#obstacleNum').value=o.n;$('#obstacleRotation').value=o.rotation;$('#obstacleLabel').value=o.label||'';if(o.type==='weave'){o.poleCount=Number(o.poleCount)===6?6:12;$('#weavePoleCount').value=String(o.poleCount)}if(['aFrame','dogWalk','tire'].includes(o.type)){const frame=o.type==='aFrame',walk=o.type==='dogWalk',heightInput=$('#obstacleHeight'),min=frame?1.2:walk?.8:.4,max=frame?2:walk?1.3:1.2,base=frame?1.7:walk?1.2:.8,height=Math.max(min,Math.min(max,Number(o.height)||base));o.height=height;heightInput.min=min;heightInput.max=max;heightInput.step='.05';heightInput.value=height;$('#obstacleHeightLabel').textContent=frame?'Wysokość szczytu':walk?'Wysokość pomostu':'Wysokość koła';$('#obstacleHeightValue').textContent=frame||walk?`${height.toFixed(2).replace('.',',')} m · nachylenie ramp ${Math.round(Math.asin(height/(frame?2.7:3.65))*180/Math.PI)}°`:`${height.toFixed(2).replace('.',',')} m`}if(o.type==='tunnel'){o.length=Number(o.length)||4.5;o.bend=Number(o.bend)||0;$('#tunnelLength').value=o.length;$('#tunnelLengthValue').textContent=`${o.length.toFixed(1).replace('.',',')} m`;$('#tunnelBend').value=o.bend;$('#tunnelBendValue').textContent=o.bend?`${o.bend}°`:'Prosty'}}
function coords(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height}}
function hit(p){const scale=state.unit==='ft'?.3048:1;for(let i=state.obstacles.length-1;i>=0;i--){const o=state.obstacles[i],size=obstacleFootprint(o),dx=(p.x-o.x)*state.length*scale,dy=(p.y-o.y)*state.width*scale,angle=(Number(o.rotation)||0)*Math.PI/180,lx=dx*Math.cos(angle)+dy*Math.sin(angle),ly=-dx*Math.sin(angle)+dy*Math.cos(angle);if(Math.abs(lx)<=size.width/2+.12&&Math.abs(ly)<=size.depth/2+.12)return o}return null}
function numberBadgeHit(p){if(!state.showNumbers)return null;const px=p.x*canvas.width,py=p.y*canvas.height,scale=state.unit==='ft'?.3048:1,pxX=canvas.width/(state.length*scale),pxY=canvas.height/(state.width*scale);for(let i=state.obstacles.length-1;i>=0;i--){const o=state.obstacles[i],{depth}=obstacleFootprint(o),items=Array.isArray(state.route)?state.route.map((visit,index)=>({visit,index})).filter(item=>(typeof item.visit==='string'?item.visit:item.visit?.obstacleId)===o.id):[],visits=items.length?items:[{visit:null,index:null}];for(let j=0;j<visits.length;j++){const {index}=visits[j],side=obstacleEntrySide(o,state,index),badgeOffset=depth/2+.48,bx=o.x*canvas.width-side*badgeOffset*Math.sin((Number(o.rotation)||0)*Math.PI/180)*pxX+(j-(visits.length-1)/2)*23,by=o.y*canvas.height+side*badgeOffset*Math.cos((Number(o.rotation)||0)*Math.PI/180)*pxY;if(Math.hypot(px-bx,py-by)<=15)return{obstacle:o,visitIndex:index}}}return null}
function rotationHandle(o){const {w,h}=dim(),scale=state.unit==='ft'?.3048:1,{depth}=obstacleFootprint(o),angle=(Number(o.rotation)||0)*Math.PI/180,offset=depth*h/(state.width*scale)/2+14,x=o.x*w+Math.sin(angle)*offset,y=o.y*h-Math.cos(angle)*offset;return{x,y,edgeX:o.x*w+Math.sin(angle)*(offset-14),edgeY:o.y*h-Math.cos(angle)*(offset-14)}}
function rotationHandleHit(p){if(!state.selected)return null;const o=state.obstacles.find(item=>item.id===state.selected);if(!o)return null;const handle=rotationHandle(o);return Math.hypot(p.x*canvas.width-handle.x,p.y*canvas.height-handle.y)<16?o:null}
function drawRotationHandle(){const o=state.obstacles.find(item=>item.id===state.selected);if(!o)return;const h=rotationHandle(o);ctx.save();ctx.setLineDash([]);ctx.lineWidth=2;ctx.strokeStyle='#e56d49';ctx.beginPath();ctx.moveTo(h.edgeX,h.edgeY);ctx.lineTo(h.x,h.y);ctx.stroke();ctx.beginPath();ctx.arc(h.x,h.y,11,0,Math.PI*2);ctx.fillStyle='#fffdf4';ctx.fill();ctx.stroke();ctx.beginPath();ctx.arc(h.x,h.y,5,-Math.PI*.8,Math.PI*.8);ctx.stroke();ctx.beginPath();ctx.moveTo(h.x+4,h.y+4);ctx.lineTo(h.x+7,h.y+2);ctx.lineTo(h.x+7,h.y+6);ctx.closePath();ctx.fillStyle='#e56d49';ctx.fill();ctx.restore()}
function nearestCurve(p){const nodes=routeNodes(),{w,h}=dim();let best=null;for(const pair of routeConnections(nodes)){const c=curveFor(nodes,pair.i,pair),pts=curveSamples(c,32);for(let j=0;j<pts.length;j++){const d=Math.hypot(pts[j].x-p.x*w,pts[j].y-p.y*h);if(!best||d<best.distance)best={curve:c,distance:d}}}return best}
function pointerDown(e){const p=coords(e),numbered=numberBadgeHit(p);if(numbered){openNumberEditor(numbered.obstacle,numbered.visitIndex);return}if(state.tool==='route'){const match=nearestCurve(p);if(!match||match.distance>26){toast('Złap uchwyt na linii trasy i przeciągnij go, aby utworzyć łuk');return}saveHistory();const c=match.curve;dragCurve={key:c.key,nx:c.nx,ny:c.ny,start:p,bend:state.routeBends[c.key]||0,moved:false};canvas.setPointerCapture(e.pointerId);return}const rotating=rotationHandleHit(p);if(rotating){saveHistory();const {w,h}=dim();dragRotation={id:rotating.id,start:Math.atan2((p.y-rotating.y)*h,(p.x-rotating.x)*w),initial:Number(rotating.rotation)||0,moved:false};canvas.setPointerCapture(e.pointerId);e.preventDefault();return}const o=hit(p);if(o){state.selected=o.id;drag={id:o.id,dx:p.x-o.x,dy:p.y-o.y,moved:false};canvas.setPointerCapture(e.pointerId)}else{state.selected=null;drag=null}updateSelection();draw()}
function pointerMove(e){const p=coords(e);$('#coord').textContent=`${(p.x*state.length).toFixed(1)} × ${(p.y*state.width).toFixed(1)} ${state.unit}`;if(dragCurve){const {w,h}=dim(),scale=Math.min(w,h),dx=(p.x-dragCurve.start.x)*w,dy=(p.y-dragCurve.start.y)*h;state.routeBends[dragCurve.key]=Math.max(-.28,Math.min(.28,dragCurve.bend+(dx*dragCurve.nx+dy*dragCurve.ny)/scale));dragCurve.moved=true;draw();return}if(dragRotation){const o=state.obstacles.find(item=>item.id===dragRotation.id);if(!o)return;const {w,h}=dim(),angle=Math.atan2((p.y-o.y)*h,(p.x-o.x)*w);let delta=angle-dragRotation.start;while(delta>Math.PI)delta-=Math.PI*2;while(delta<-Math.PI)delta+=Math.PI*2;const raw=dragRotation.initial+delta*180/Math.PI;o.rotation=((raw+180)%360+360)%360-180;dragRotation.moved=true;$('#obstacleRotation').value=Math.round(o.rotation);draw();return}if(!drag){canvas.style.cursor=rotationHandleHit(p)?'grab':'';return}const o=state.obstacles.find(o=>o.id===drag.id);if(!o)return;if(!drag.moved){saveHistory();drag.moved=true}o.x=Math.max(.06,Math.min(.94,p.x-drag.dx));o.y=Math.max(.08,Math.min(.92,p.y-drag.dy));draw();updateRouteList()}
function pointerUp(){if(drag?.moved||dragCurve?.moved||dragRotation?.moved)markDirty();drag=null;dragCurve=null;dragRotation=null;canvas.style.cursor='' }
function shuffle(list){for(let i=list.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[list[i],list[j]]=[list[j],list[i]]}return list}
function courseObstaclePool(mode,count){
 const rand=(a,b)=>a+Math.random()*(b-a),pick=a=>a[Math.floor(Math.random()*a.length)],tunnel=(short=false)=>({type:'tunnel',length:short?3.5:rand(4.5,6),bend:pick([0,0,15,30,45,60,75,90])});
 let pool=[];
 if(mode==='training'){if(count===1)pool.push({type:'jump'});else{const tunnels=Math.min(4,Math.max(1,Math.round(count*.24)),count-2);pool=[...Array(count-tunnels)].map(()=>({type:'jump'}));pool.push(tunnel(true),...Array.from({length:tunnels-1},()=>tunnel()))}}
 else{
  pool=[...Array(7)].map(()=>({type:'jump'}));pool.push({type:'aFrame'},{type:'dogWalk'},{type:'seesaw'},{type:'weave'},tunnel(true),{type:'tire'},{type:'wall'},{type:'longJump'});
  while(pool.length<count)pool.push(Math.random()<.78?{type:'jump'}:tunnel());
  if(Math.random()<.55){const jump=pool.findIndex(o=>o.type==='jump');if(jump>=0)pool[jump]={type:'spread'}}
 }
 shuffle(pool);if(pool.length===1)pool[0]={type:'jump'};else{let first=pool.findIndex(o=>o.type==='jump');if(first>0)[pool[0],pool[first]]=[pool[first],pool[0]];const last=pool.map(o=>o.type).lastIndexOf('jump');if(last>=0&&last<pool.length-1)[pool[pool.length-1],pool[last]]=[pool[last],pool[pool.length-1]]}
 return pool;
}
function rotatedObstacleBox(o,x,y,rotation){const s=obstacleFootprint(o),a=rotation*Math.PI/180,c=Math.cos(a),sn=Math.sin(a);return[[-s.width/2,-s.depth/2],[s.width/2,-s.depth/2],[s.width/2,s.depth/2],[-s.width/2,s.depth/2]].map(([px,py])=>({x:x+px*c-py*sn,y:y+px*sn+py*c}))}
function boxesOverlap(a,b,pad=.12){for(const poly of[a,b])for(let i=0;i<poly.length;i++){const p=poly[i],q=poly[(i+1)%poly.length],ax=-(q.y-p.y),ay=q.x-p.x,len=Math.hypot(ax,ay)||1,nx=ax/len,ny=ay/len;const aa=a.map(v=>v.x*nx+v.y*ny),bb=b.map(v=>v.x*nx+v.y*ny);if(Math.max(...aa)+pad<Math.min(...bb)||Math.max(...bb)+pad<Math.min(...aa))return false}return true}
function randomCourse(mode,count){
 saveHistory();const competition=mode==='competition',rand=(a,b)=>a+Math.random()*(b-a),pick=a=>a[Math.floor(Math.random()*a.length)],pool=courseObstaclePool(mode,count),n=pool.length;
 const span=o=>o.type==='weave'?Math.max(.6,((Number(o.poleCount)===6?6:12)-1)*.6+.6):o.type==='tunnel'?Math.hypot(...(()=>{const p=tunnelPath(o.length,o.bend,1);return[p.at(-1).x-p[0].x,p.at(-1).y-p[0].y]})()):obstacleFootprint(o).depth;
 state.length=40;state.width=24;state.unit='m';state.gridSize=2;
 let course=null;
 // Build a free-form path from random start points and turn sequences. Reject edge exits and equipment collisions.
 for(let attempt=0;attempt<2400&&!course;attempt++){
  const spreadFactor=n<=6?1.32:n<=10?1.16:n>=16?.72:n>=12?.82:1,gapMax=competition?6.9:7.6,gaps=Array.from({length:n-1},()=>rand(5.2,gapMax)*spreadFactor),spans=pool.map(span),bearings=[rand(-Math.PI,Math.PI)],entry={x:rand(3,37),y:rand(3,21)},estimate={x:entry.x,y:entry.y};
  const turns=[-145,-120,-95,-70,-45,-25,25,45,70,95,120,145].map(value=>value*Math.PI/180);
  for(let i=1;i<n-1;i++){const step=spans[i-1]/2+gaps[i-1]+spans[i]/2,options=turns.map(delta=>({angle:bearings[i-1]+delta,delta}));shuffle(options);let best=null;for(const option of options){const x=estimate.x+Math.cos(option.angle)*step,y=estimate.y+Math.sin(option.angle)*step,edge=Math.max(0,2.1-x,x-37.9,2.1-y,y-21.9),score=edge*100+Math.hypot(x-20,y-12)*.025+Math.abs(option.delta)*.01+Math.random()*.55;if(!best||score<best.score)best={...option,x,y,score}}bearings.push(best.angle);estimate.x=best.x;estimate.y=best.y}
  // Smooth obstacle axes between the approach and departure directions.
  const axes=pool.map((_,i)=>{if(i===0)return bearings[0];if(i===n-1)return bearings.at(-1);const a=bearings[i-1],b=bearings[i],x=Math.cos(a)+Math.cos(b),y=Math.sin(a)+Math.sin(b);return Math.hypot(x,y)<.15?b:Math.atan2(y,x)});
  const candidate=[],boxes=[];let portal=entry,valid=true;
  for(let i=0;i<n;i++){
   const item=pool[i],axis=axes[i],center={x:portal.x+Math.cos(axis)*spans[i]/2,y:portal.y+Math.sin(axis)*spans[i]/2};
   const rotation=(axis*180/Math.PI-(item.type==='weave'?0:90)),box=rotatedObstacleBox(item,center.x,center.y,rotation);
   const edgeMargin=n<=6?.35:n<=10?.45:.55;if(box.some(p=>p.x<edgeMargin||p.x>40-edgeMargin||p.y<edgeMargin||p.y>24-edgeMargin)){valid=false;break}
   if(boxes.some((other,j)=>boxesOverlap(box,other,.18)&&!(pool[i].type===pool[j].type&&(pool[i].type!=='tunnel'||(Math.abs((Number(pool[i].bend)||0)-(Number(pool[j].bend)||0))<1&&Math.abs((Number(pool[i].length)||0)-(Number(pool[j].length)||0))<.01))))){valid=false;break}
   boxes.push(box);candidate.push({...item,x:center.x/40,y:center.y/24,rotation,n:i+1,id:id(),label:''});
   portal={x:center.x+Math.cos(axis)*spans[i]/2,y:center.y+Math.sin(axis)*spans[i]/2};
   if(i<n-1)portal={x:portal.x+Math.cos(bearings[i])*gaps[i],y:portal.y+Math.sin(bearings[i])*gaps[i]};
  }
    if(valid&&candidate.length===n){
   if(n<=10){
    const boundsFor=list=>{const pts=list.flatMap(o=>rotatedObstacleBox(o,o.x*40,o.y*24,o.rotation));return{xMin:Math.min(...pts.map(p=>p.x)),xMax:Math.max(...pts.map(p=>p.x)),yMin:Math.min(...pts.map(p=>p.y)),yMax:Math.max(...pts.map(p=>p.y))}};
    const bounds=boundsFor(candidate),targetWidth=38,targetHeight=22,scale=Math.min(1.65,targetWidth/Math.max(.01,bounds.xMax-bounds.xMin),targetHeight/Math.max(.01,bounds.yMax-bounds.yMin));
    if(scale>=1.08){const cx=(bounds.xMin+bounds.xMax)/2,cy=(bounds.yMin+bounds.yMax)/2,stretched=candidate.map(o=>({...o,x:(20+(o.x*40-cx)*scale)/40,y:(12+(o.y*24-cy)*scale)/24})),stretchedBounds=boundsFor(stretched);if(stretchedBounds.xMin>=.4&&stretchedBounds.xMax<=39.6&&stretchedBounds.yMin>=.4&&stretchedBounds.yMax<=23.6)course=stretched}
   }
   if(!course)course=candidate;
  }
 }
 if(!course)throw Error('Nie udało się bezkolizyjnie ułożyć toru. Spróbuj ponownie.');
 state.obstacles=course;state.route=[];state.routeBends={};state.selected=null;state.tool='select';state.view='2d';state.showRoute=true;state.showNumbers=true;state.showDistances=true;$('#leftPanel').classList.remove('mobile-open');$('#showTools').classList.remove('active');
 state.title=competition?`Tor losowy — ${count} przeszkód`:`Tor treningowy — ${count} przeszkód`;sync();draw();markDirty();
 toast(competition?`Wylosowano tor ${count} przeszkód. Zweryfikuj przed treningiem.`:`Wylosowano treningowy tor ${count} przeszkód.`);
}
function addObstacle(type){if(!names[type])return showError('Nieznany typ przeszkody.');if(state.obstacles.length>=99)return showError('Możesz dodać maksymalnie 99 przeszkód.');const used=new Set(state.obstacles.map(o=>Number(o.n)));let n=1;while(used.has(n)&&n<=99)n++;if(n>99)return showError('Brak wolnego numeru przeszkody.');const explicit=routeNodes().map(o=>o._visitIndex!=null?state.route[o._visitIndex]:o.id);saveHistory();const o={id:id(),type,x:.5,y:.5,n,label:'',rotation:0};if(type==='tunnel'){o.length=4.5;o.bend=0}if(type==='weave')o.poleCount=12;if(type==='aFrame')o.height=1.7;if(type==='tire')o.height=.8;if(type==='dogWalk')o.height=1.2;state.obstacles.push(o);if(state.route?.length)state.route=explicit.concat(o.id);state.selected=o.id;state.tool='select';sync();draw();toast(`${names[type]} dodana do planszy`)}
function deleteSelected(){if(!state.selected)return;saveHistory();const deleted=state.selected;state.obstacles=state.obstacles.filter(o=>o.id!==deleted);if(Array.isArray(state.route))state.route=state.route.filter(visit=>(typeof visit==='string'?visit:visit?.obstacleId)!==deleted);const ordered=[...state.obstacles].sort((a,b)=>a.n-b.n),numbers=[...new Set(ordered.map(o=>Number(o.n)))];const remap=new Map(numbers.map((n,i)=>[n,i+1]));ordered.forEach(o=>o.n=remap.get(Number(o.n)));state.selected=null;updateSelection();updateRouteList();draw();markDirty();toast('Usunięto przeszkodę i zaktualizowano numery')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('error');t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1900)}
function autosave(){try{localStorage.setItem('agility-map-project',JSON.stringify({...state,selected:null,tool:'select'}));$('#saveState').textContent='Zapisano lokalnie';$('#saveState').parentElement.querySelector('i').style.background='var(--lime)'}catch(error){$('#saveState').textContent='Błąd zapisu';showError(`Nie udało się zapisać projektu w przeglądarce: ${error.message}`)}}
function markDirty(){ $('#saveState').textContent='Zapisywanie…';$('#saveState').parentElement.querySelector('i').style.background='var(--orange)';clearTimeout(changedTimer);changedTimer=setTimeout(autosave,450)}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportJSON(){try{download(new Blob([JSON.stringify({...state,selected:null,tool:'select'},null,2)],{type:'application/json'}),`${slug(state.title)}.json`);toast('Projekt zapisany do pliku')}catch(error){showError(`Eksport projektu nie powiódł się: ${error.message}`)}}
function slug(s){return (s||'tor-agility').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'tor-agility'}
function exportPNG(){try{const source=state.view==='3d'&&scene3d?scene3d.renderer.domElement:canvas,copy=document.createElement('canvas');copy.width=source.width;copy.height=source.height;const c=copy.getContext('2d');c.drawImage(source,0,0);copy.toBlob(b=>{if(b){download(b,`${slug(state.title)}.png`);toast('Eksport PNG gotowy')}else showError('Nie udało się przygotować obrazu PNG.')},'image/png')}catch(error){showError(`Eksport PNG nie powiódł się: ${error.message}`)}}
function toggle(id,key){state[key]=!state[key];setSwitch(id,state[key]);if(key==='showRoute')setSwitch(id==='routeSwitch'?'routeSwitch2':'routeSwitch',state[key]);draw();markDirty()}
async function setView(view){if(view==='2d'){state.view='2d';sync();$('#hint').innerHTML=state.tool==='route'?'<b>Trasa automatyczna</b> · Przeciągnij uchwyt na linii, aby zmienić łuk':'<b>Wskazówka</b> · Kliknij numer, aby go zmienić; przeciągnij uchwyt nad przeszkodą, aby obrócić';draw();markDirty();return}state.view='3d';sync();$('#hint').innerHTML='<b>Widok 3D</b> · Alt + przeciągnij przeszkodę, aby ją obrócić; Shift + przeciągnij lub prawy przycisk przesuwa kamerę';try{if(!scene3d){if(!scene3dLoading)scene3dLoading=(async()=>{const {createScene3D}=await import('./scene-3d.js?v=agility-alternate-track-color-20261003');return createScene3D({canvas:$('#scene3dCanvas'),getState:()=>state,onSelect:id=>{state.selected=id;updateSelection();draw()},onEditNumber:(id,visitIndex)=>{const obstacle=state.obstacles.find(item=>item.id===id);if(obstacle)openNumberEditor(obstacle,visitIndex)},onRotate:(id,rotation)=>{const obstacle=state.obstacles.find(item=>item.id===id);if(obstacle){obstacle.rotation=rotation;document.getElementById("obstacleRotation").value=rotation;draw()}},onMove:(id,x,y)=>{const o=state.obstacles.find(item=>item.id===id);if(o){o.x=x;o.y=y;$('#coord').textContent=`${(x*state.length).toFixed(1)} × ${(y*state.width).toFixed(1)} ${state.unit}`;draw();updateRouteList()}},onBend:(key,value)=>{state.routeBends[key]=value;draw()},onDone:markDirty,onError:message=>{if(state.view==='3d'){state.view='2d';sync();draw()}showError(message)}})})();scene3d=await scene3dLoading}draw();markDirty()}catch(error){scene3d=null;scene3dLoading=null;state.view='2d';sync();draw();showError(`Nie udało się uruchomić widoku 3D. Sprawdź obsługę WebGL i połączenie z internetem. (${error.message})`)}}
$('#tools').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tool)setTool(b.dataset.tool);if(b.dataset.add)addObstacle(b.dataset.add)});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',pointerUp);canvas.addEventListener('dblclick',()=>{if(state.tool==='route')setTool('select')});
$('#randomCourse').onclick=()=>$('#randomCourseDialog').showModal();$('#randomCourseDialog').addEventListener('click',e=>{const button=e.target.closest('[data-random-mode]');if(!button)return;const field=$('#courseObstacleCount'),count=Number(field.value),mode=button.dataset.randomMode;if(!Number.isInteger(count)||count<1||count>20){field.setCustomValidity('Wybierz od 1 do 20 przeszkód.');field.reportValidity();return}if(mode==='competition'&&count<15){field.setCustomValidity('Tor standardowy FCI musi zawierać co najmniej 15 przeszkód. Wybierz tryb treningowy dla mniejszego toru.');field.reportValidity();return}field.setCustomValidity('');$('#randomCourseDialog').close();try{randomCourse(mode,count)}catch(error){showError(error.message)}});
const tutorialPages=[
 {title:'Plansza i wybieranie',body:'Plansza pokazuje tor z góry. Kliknij przeszkodę, aby ją zaznaczyć, i przeciągnij, aby zmienić położenie. Klawisz Delete usuwa zaznaczoną przeszkodę. Przyciski cofania i ponawiania znajdziesz w górnym pasku; działają też skróty Ctrl+Z i Ctrl+Y.'},
 {title:'Dodawanie przeszkód',body:'W panelu Narzędzia dodasz skok pojedynczy lub podwójny, ścianę, skok w dal, koło, palisadę A, kładkę, huśtawkę, tunel i slalom. Kliknij ikonę, a przeszkoda pojawi się na planszy. Przeciągnij ją na miejsce.'},
 {title:'Kolejność i numery',body:'Trasa przechodzi przez przeszkody według numerów. Zaznacz przeszkodę i zmień jej numer w panelu po prawej. Numer może być wspólny dla różnych przeszkód. Użyj przycisku „Dodaj wariant toru”, aby utworzyć alternatywną przeszkodę z tym samym numerem; trasa rozgałęzi się na wariantach i połączy przy kolejnym numerze. „Dodaj kolejne przejście” ponownie wykorzystuje tę samą przeszkodę.'},
 {title:'Rysowanie trasy i łuków',body:'Przebieg trasy tworzy się automatycznie między kolejnymi przeszkodami i prowadzi przez ich obszar, w tym przez krzywiznę tunelu. Wybierz narzędzie Trasa i przeciągnij uchwyt na odcinku, aby zmienić łuk. „Przywróć automatyczne łuki” usuwa ręczne korekty.'},
 {title:'Ustawienia przeszkody',body:'Po zaznaczeniu przeszkody możesz zmienić jej numer, obrót i etykietę. Palisada A, kładka i koło mają regulowaną wysokość; nachylenie ramp zmienia się razem z wysokością. Slalom może mieć 6 tyczek do treningu albo pełne 12. Dla tunelu ustaw długość oraz krzywiznę; 0° oznacza tunel prosty. „Dodaj kolejne przejście” ponownie wstawia przeszkodę do kolejności toru.'},
 {title:'Wymiary i wygląd planszy',body:'Panel Ustawienia planszy pozwala zmienić długość i szerokość, rozmiar siatki oraz jednostki metryczne lub stopy. Współrzędne siatki są opisane w metrach, a etykieta nad planszą pokazuje aktualną skalę 1 m w pikselach. Możesz też zmienić kolory. Przyciski +/− zmieniają powiększenie.'},
 {title:'Warstwy i odległości',body:'Włączaj lub wyłączaj siatkę, trasę i numery. „Pokaż odległości” wyświetla długości odcinków między kolejnymi przeszkodami. Te przełączniki działają również w widoku 3D.'},
 {title:'Widok 2D i 3D',body:'Przełącz widok przyciskami 2D i 3D. Przeciągnij uchwyt nad zaznaczoną przeszkodą, aby obrócić ją w 2D. W 3D użyj Alt + przeciągnięcie na przeszkodzie; przeciągnięcie tła obraca kamerę, Shift lub prawy przycisk przesuwa widok. Kliknij numer na planszy, aby go edytować.'},
 {title:'Losowanie toru',body:'Kliknij „Losuj tor”, wybierz liczbę od 1 do 20 i rodzaj układu. Skok pojedynczy zawsze otwiera i kończy wygenerowany tor. Tryb treningowy obsługuje mniejsze układy i zawiera tylko skoki pojedyncze oraz tunele. Tryb standardowy wymaga co najmniej 15 przeszkód. Generator losuje punkt startu i przebieg, a układy z kolizjami odrzuca. Przed treningiem zweryfikuj tor.'},
 {title:'Zapisywanie i telefon',body:'Projekt zapisuje się automatycznie w tej przeglądarce. „Projekt” eksportuje plik JSON, a ikona importu w pasku planszy wczytuje taki plik. „Eksportuj PNG” zapisuje obraz toru. Na telefonie dolne przyciski Narzędzia i Ustawienia otwierają przesuwane panele.'}
];
let tutorialIndex=0;function renderTutorial(){const page=tutorialPages[tutorialIndex];$('#tutorialStep').innerHTML=`<h2>${page.title}</h2><p>${page.body}</p>`;$('#tutorialCount').textContent=`${tutorialIndex+1} / ${tutorialPages.length}`;$('#tutorialProgress').style.width=`${(tutorialIndex+1)/tutorialPages.length*100}%`;$('#tutorialPrev').disabled=tutorialIndex===0;$('#tutorialNext').textContent=tutorialIndex===tutorialPages.length-1?'Zakończ':'Dalej'}
function openTutorial(){tutorialIndex=0;renderTutorial();$('#tutorialDialog').showModal()}
$('#tutorialOpen').onclick=openTutorial;$('#tutorialPrev').onclick=()=>{if(tutorialIndex>0){tutorialIndex--;renderTutorial()}};$('#tutorialNext').onclick=()=>{if(tutorialIndex<tutorialPages.length-1){tutorialIndex++;renderTutorial()}else $('#tutorialDialog').close()};$('#tutorialPrompt').addEventListener('close',()=>{try{localStorage.setItem('agility-map-tutorial-prompt-v1','1')}catch{}if($('#tutorialPrompt').returnValue==='start')openTutorial()});
let tutorialPrompted=false,termsAccepted=false;try{tutorialPrompted=localStorage.getItem('agility-map-tutorial-prompt-v1')==='1';termsAccepted=localStorage.getItem('agility-map-terms-v1')==='1'}catch{}
$('#termsOpen').onclick=()=>$('#termsDialog').showModal();$('#termsDialog').addEventListener('cancel',e=>{if(!termsAccepted)e.preventDefault()});$('#acceptTerms').onclick=()=>{termsAccepted=true;try{localStorage.setItem('agility-map-terms-v1','1')}catch{}$('#termsDialog').close();if(!tutorialPrompted)$('#tutorialPrompt').showModal()};
$('#privacyOpen').onclick=()=>$('#privacyDialog').showModal();$('#closePrivacy').onclick=()=>$('#privacyDialog').close();
$('#undo').onclick=undo;$('#redo').onclick=redo;$('#exportPng').onclick=exportPNG;$('#saveJson').onclick=exportJSON;$('#importJson').onclick=()=>$('#filePicker').click();$('#filePicker').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onerror=()=>showError('Nie udało się odczytać pliku projektu.');rd.onload=()=>{const before={...state};try{const q=JSON.parse(rd.result);if(Array.isArray(q.obstacles))q.obstacles=q.obstacles.filter(o=>!['chute','triple'].includes(o.type));if(!Array.isArray(q.obstacles)||q.obstacles.length>99)throw Error('Plik musi zawierać listę maksymalnie 99 przeszkód.');if(!Number.isFinite(q.length)||q.length<5||q.length>100||!Number.isFinite(q.width)||q.width<5||q.width>100)throw Error('Wymiary planszy muszą mieścić się w zakresie 5–100.');if(q.unit&&!['m','ft'].includes(q.unit))throw Error('Nieznana jednostka miary.');if(!Array.isArray(q.route))q.route=[];if(q.obstacles.some(o=>!names[o.type]&&!['table','marker','chute','triple'].includes(o.type)))throw Error('Plik zawiera nieznany typ przeszkody.');if(q.obstacles.some(o=>![o.x,o.y].every(Number.isFinite)||o.x<0||o.x>1||o.y<0||o.y>1))throw Error('Położenie przeszkody poza planszą.');saveHistory();Object.assign(state,q);state.routeBends||={};state.showDistances=!!q.showDistances;state.obstacles=state.obstacles.filter(o=>!['table','marker','chute','triple'].includes(o.type));const ids=new Set();for(const o of state.obstacles){if(!o.id||ids.has(o.id))o.id=id();ids.add(o.id)}state.view=state.view==='3d'?'3d':'2d';state.tool='select';const changed=normalizeOrderNumbers();state.selected=null;sync();if(state.view==='3d')setView('3d');else draw();autosave();if(changed)showError('Projekt miał powtórzone numery. Nadałem im unikalne numery.');else toast('Projekt wczytany')}catch(error){Object.assign(state,before);sync();draw();showError(`Nie udało się wczytać projektu: ${error.message}`)}};rd.readAsText(f);e.target.value=''};
$('#gridSwitch').onclick=()=>toggle('gridSwitch','grid');$('#routeSwitch').onclick=()=>toggle('routeSwitch','showRoute');$('#routeSwitch2').onclick=()=>toggle('routeSwitch2','showRoute');$('#numberSwitch').onclick=()=>toggle('numberSwitch','showNumbers');$('#distanceSwitch').onclick=()=>toggle('distanceSwitch','showDistances');$('#clearRoute').onclick=()=>{if(!Object.keys(state.routeBends||{}).length)return;saveHistory();state.routeBends={};draw();updateRouteList();markDirty();toast('Przywrócono automatyczne łuki')};$('#clearCourse').onclick=()=>{saveHistory();state.obstacles=[];state.route=[];state.routeBends={};state.selected=null;sync();draw();markDirty();toast('Plansza wyczyszczona')};$('#deleteObstacle').onclick=deleteSelected;$('#variantObstacle').onclick=()=>{const source=state.obstacles.find(o=>o.id===state.selected);if(!source)return;if(state.obstacles.length>=99)return showError('Możesz dodać maksymalnie 99 przeszkód.');saveHistory();const variant={...source,id:id(),x:Math.max(.06,Math.min(.94,source.x+.045)),y:Math.max(.08,Math.min(.92,source.y+.045))};state.obstacles.push(variant);if(Array.isArray(state.route)&&state.route.length){const index=state.route.indexOf(source.id);if(index>=0)state.route.splice(index+1,0,variant.id)}state.selected=variant.id;sync();draw();markDirty();toast(`Dodano wariant przeszkody nr ${variant.n}`)};$('#repeatObstacle').onclick=()=>{const obstacle=state.obstacles.find(o=>o.id===state.selected);if(!obstacle)return;const nodes=routeNodes();if(nodes.length>=99)return showError('Tor może zawierać maksymalnie 99 przejść.');saveHistory();state.route=nodes.map(o=>o._visitIndex!=null?state.route[o._visitIndex]:o.id);state.route.push(obstacle.id);draw();updateRouteList();markDirty();toast(`Dodano kolejne przejście nr ${obstacle.n}; trasa została przeliczona`)};
$('#obstacleNum').onchange=e=>{const o=state.obstacles.find(o=>o.id===state.selected),number=Math.max(1,Math.min(99,Math.floor(+e.target.value||1)));if(!o)return;saveHistory();o.n=number;if(Array.isArray(state.route)&&state.route.length){const sibling=state.obstacles.find(item=>item.id!==o.id&&Number(item.n)===number);if(sibling){const currentIndex=state.route.indexOf(o.id);if(currentIndex>=0)state.route.splice(currentIndex,1);const siblingIndex=state.route.indexOf(sibling.id);if(siblingIndex>=0)state.route.splice(siblingIndex+1,0,o.id)}}draw();updateRouteList();markDirty()};$('#obstacleRotation').onfocus=()=>saveHistory();$('#obstacleRotation').oninput=e=>{const o=state.obstacles.find(o=>o.id===state.selected);if(o){o.rotation=Math.max(-180,Math.min(180,+e.target.value||0));draw();markDirty()}};$('#obstacleHeight').onpointerdown=()=>saveHistory();$('#obstacleHeight').oninput=e=>{const o=state.obstacles.find(o=>o.id===state.selected);if(o&&['aFrame','dogWalk','tire'].includes(o.type)){o.height=+e.target.value;if(o.type==='tire')$('#obstacleHeightValue').textContent=`${o.height.toFixed(2).replace('.',',')} m`;else{const run=o.type==='aFrame'?2.7:3.65;$('#obstacleHeightValue').textContent=`${o.height.toFixed(2).replace('.',',')} m · nachylenie ramp ${Math.round(Math.asin(o.height/run)*180/Math.PI)}°`}draw();markDirty()}};$('#weavePoleCount').onchange=e=>{const o=state.obstacles.find(item=>item.id===state.selected);if(!o||o.type!=='weave')return;saveHistory();o.poleCount=Number(e.target.value)===6?6:12;draw();updateRouteList();markDirty();toast('Zmieniono liczbę tyczek slalomu')};$('#tunnelLength').onpointerdown=()=>saveHistory();$('#tunnelLength').oninput=e=>{const o=state.obstacles.find(o=>o.id===state.selected);if(o?.type==='tunnel'){o.length=+e.target.value;$('#tunnelLengthValue').textContent=`${o.length.toFixed(1).replace('.',',')} m`;draw();markDirty()}};$('#tunnelBend').onpointerdown=()=>saveHistory();$('#tunnelBend').oninput=e=>{const o=state.obstacles.find(o=>o.id===state.selected);if(o?.type==='tunnel'){o.bend=+e.target.value;$('#tunnelBendValue').textContent=o.bend?`${o.bend}°`:'Prosty';draw();markDirty()}};$('#obstacleLabel').oninput=e=>{const o=state.obstacles.find(o=>o.id===state.selected);if(o){o.label=e.target.value;draw();updateRouteList();markDirty()}};
$('#numberEditSave').onclick=()=>{const obstacle=state.obstacles.find(item=>item.id===state.selected),value=Number($('#numberEditValue').value);if(!obstacle)return $('#numberEditDialog').close();if(!Number.isInteger(value)||value<1||value>99){showError('Numer musi być liczbą całkowitą od 1 do 99.');$('#numberEditValue').focus();return}if(editingVisitIndex!=null){saveHistory();state.route[editingVisitIndex]={obstacleId:obstacle.id,n:value};editingVisitIndex=null;$('#numberEditDialog').close();draw();updateRouteList();markDirty();return}$('#obstacleNum').value=value;$('#obstacleNum').dispatchEvent(new Event('change'));$('#numberEditDialog').close()};$('#numberEditDialog').addEventListener('close',()=>{editingVisitIndex=null});const fields={title:'title',settingsTitle:'title',length:'length',width:'width',gridSize:'gridSize',unit:'unit',bgColor:'bg',obColor:'ob',pathColor:'path'};Object.keys(fields).forEach(id=>{$('#'+id).addEventListener('input',e=>{const k=fields[id];if(k==='length'||k==='width'){state[k]=Math.max(5,Math.min(100,+e.target.value||40));e.target.value=state[k]}else if(k==='gridSize'){state[k]=Math.max(.5,Math.min(5,+e.target.value||1));e.target.value=state[k]}else state[k]=e.target.value;if(k==='unit')document.querySelectorAll('[data-board-unit]').forEach(el=>el.textContent=state.unit);if(k==='title'){ $('#title').value=state.title;$('#settingsTitle').value=state.title}draw();updateRouteList();markDirty()})});
$('#zoomIn').onclick=()=>{state.zoom=Math.min(150,state.zoom+10);applyZoom()};$('#zoomOut').onclick=()=>{state.zoom=Math.max(60,state.zoom-10);applyZoom()};$('#fit').onclick=()=>{state.zoom=100;applyZoom()};
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo()}else if(e.key==='Delete'||e.key==='Backspace')deleteSelected();else if(e.key==='Escape')setTool('select')});
$('#showTools').onclick=()=>{const open=!$('#leftPanel').classList.contains('mobile-open');$('#leftPanel').classList.toggle('mobile-open',open);$('#rightPanel').classList.remove('mobile-open');$('#showTools').classList.toggle('active',open);$('#showSettings').classList.remove('active')};$('#showSettings').onclick=()=>{const open=!$('#rightPanel').classList.contains('mobile-open');$('#rightPanel').classList.toggle('mobile-open',open);$('#leftPanel').classList.remove('mobile-open');$('#showSettings').classList.toggle('active',open);$('#showTools').classList.remove('active')};
window.addEventListener('agility-icons-ready',()=>draw());window.addEventListener('agility-asset-error',e=>showError(`Nie udało się wczytać ikony ${e.detail}.`));window.addEventListener('error',e=>{if(e.target instanceof HTMLImageElement)return;showError('Wystąpił nieoczekiwany błąd aplikacji.')});window.addEventListener('unhandledrejection',()=>showError('Nie udało się ukończyć jednej z operacji. Spróbuj ponownie.'));
const boardResizeObserver=new ResizeObserver(()=>{applyZoom();if(state.view==='3d'&&scene3d)scene3d.update(state)});boardResizeObserver.observe(canvasWrap);window.addEventListener('resize',()=>{applyZoom();if(state.view==='3d'&&scene3d)scene3d.update(state)});
let current=null,legacy=null;try{current=localStorage.getItem('agility-map-project');legacy=localStorage.getItem('torownik-project')}catch(error){showError(`Przeglądarka zablokowała zapis lokalny: ${error.message}`)}const old=current||legacy;if(old){try{Object.assign(state,JSON.parse(old));state.routeBends||={};state.showDistances=!!state.showDistances;state.obstacles=state.obstacles.filter(o=>!['table','marker','chute','triple'].includes(o.type));const changed=normalizeOrderNumbers();state.view=state.view==='3d'?'3d':'2d';state.tool='select';state.selected=null;if(!current&&legacy)localStorage.setItem('agility-map-project',JSON.stringify(state));if(changed){showError('W zapisanym torze były powtórzone numery. Nadałem im unikalne numery.');autosave()}}catch(error){seed();showError(`Nie udało się odczytać zapisanego projektu. Wczytałem pusty tor. (${error.message})`)}}else seed();sync();if(state.view==='3d')setView('3d');else draw();requestAnimationFrame(()=>{applyZoom();if(state.view==='3d'&&scene3d)scene3d.update(state);else draw()});if(!termsAccepted)$('#termsDialog').showModal();else if(!tutorialPrompted)$('#tutorialPrompt').showModal();
})()



